#!/bin/bash
set -e
set -v
birgit_="`dirname \"$0\"`"
target_commit="$($birgit_/hash $1 HEAD)"

#no previous fixups/squashes allowed
$birgit_/commitMessageExists $target_commit fixup! &>/dev/null && echo "Will not continue because of existing fixup! found in shared history. Please run git rebase --autosquash " && exit 0 || true
$birgit_/commitMessageExists $target_commit squash! &>/dev/null && echo "Will not continue because of existing squash! found in shared history.  Please run git rebase --autosquash "  && exit 0 || true

#target and its parent must be shared history of HEAD
$birgit_/contains $target_commit > /dev/null
$birgit_/contains $target_commit^ > /dev/null

#target should not be shared repository origin/master
$birgit_/shared target_commit > /dev/null && ( echo "Changing history on shared history is not permitted" ; exit 1 ) || true

git commit -n --fixup=$target_commit
GIT_SEQUENCE_EDITOR="cat" git rebase $target_commit^ -i --autosquash --autostash --preserve-merges
