#!/bin/bash
set -e
birgit_="`dirname \"$0\"`"
target_commit="$($birgit_/hash $1 HEAD)"
amend_name="birgit amend $target_commit $(date --rfc-3339=ns )"
git commit -m ""
NEWCHANGES="$($birgit_/hash HEAD)"
git stash save $amend_name
git checkout HEAD^
REBASE_DATA="pick $target_commit
squash $NEWCHANGES
$($birgit_/helper_/commitIDSince $target_commit | sed 's/^/pick /g' | tac)"
GIT_SEQUENCE_EDITOR="echo '$REBASE_DATA' >" git rebase -i $target_commit^
git stash pop
