#!/usr/bin/env bash
birgit_=$(dirname $0)
if [ $1 ] ;then
	CMD="$birgit_/birgit_/$1"
	if [ -x $CMD ] ;	then
		$CMD ${*:2}
	else
		echo Not av valid comand: ${*}
		birgit
	fi
else
	find $birgit_/beta_ -maxdepth 1 -perm -111 -type f | xargs basename -a | sort
fi
