#!/usr/bin/env bash
set -e
birgit_="`dirname \"$0\"`"
commitToFind="$($birgit_/hash $1)"
historyOf=HEAD

if [ $2 ]; then
	historyOf=$commitToFind
	commitToFind="$($birgit_/hash $2)"
fi
git log $historyOf --pretty=format:'%H' | grep "$commitToFind" || ( echo "not found" ; exit 1 )

