#!/usr/bin/env bash
birgit_="`dirname \"$0\"`"

n=" -n10 " #Number of items to show
graph="--graph"
oneline="--oneline"
decorate="--decorate"
topo_order="--topo-order"

#git configuration
gitConf="-c color.ui=always"
no_pager="--no-pager"
for i in "$@"
do
	case $i in
		--help)
			echo 'Display log in pretty format, should honor standard git log arguments. with some defaults'
			exit 0
			;;
		-n*)
			n=""
			;;
	esac
	args="$args $i"
done

git $gitConf $no_pager log $args $graph $decorate $topo_order $n --pretty=format:'%h%Creset -%C(yellow)%d %Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'
