#!/usr/bin/env bash

commit="HEAD"
MY_PATH="`dirname \"$0\"`"


hash=$($MY_PATH/hash $commit)


CMD=$*

tmpdir=$(mktemp -d -t birigt-"$hash"-XXX)
git worktree add $tmpdir &>/dev/null
pushd $tmpdir &>/dev/null
    sh -c "$CMD"
popd &>/dev/null
git worktree remove $tmpdir &>/dev/null
rm -rf $tmpdir
