#!/bin/bash
#defaults
b=0 #Age of tages
n=1 #Number of items to show

for i in "$@"
do
	case $i in
		-n*)
			n="${i#*n}"
			shift
			;;
		-b*)
			b="${i#*b}"
			shift
			;;
		--help)
			echo $'-n*, -n10 to show 10 tags \n-b* to start show older tags, 0 i latest'
			exit 0
			;;
	esac
done

b=$((b+n))
git for-each-ref --format='%(*committerdate:raw)%(committerdate:raw) %(refname) %(*objectname) %(objectname)' refs/tags | \
	sort -n | awk '{ print $3; }' | tail -$b | head -$n
